"""Auto-generated by tools/gen_ffi.py. Do not edit by hand."""

CDEF = r'''
       
       
       
typedef void* b3AllocFcn( int32_t size, int32_t alignment );
typedef void b3FreeFcn( void* mem );
typedef int b3AssertFcn( const char* condition, const char* fileName, int lineNumber );
typedef void b3LogFcn( const char* message );
 void b3SetAllocator( b3AllocFcn* allocFcn, b3FreeFcn* freeFcn );
 int32_t b3GetByteCount( void );
 void b3SetAssertFcn( b3AssertFcn* assertFcn );
 int b3InternalAssert( const char* condition, const char* fileName, int lineNumber );
 void b3SetLogFcn( b3LogFcn* logFcn );
typedef struct b3Version
{
 int major;
 int minor;
 int revision;
} b3Version;
 b3Version b3GetVersion( void );
 bool b3IsDoublePrecision( void );
 uint64_t b3GetTicks( void );
 float b3GetMilliseconds( uint64_t ticks );
 float b3GetMillisecondsAndReset( uint64_t* ticks );
 void b3Yield( void );
 void b3Sleep( int milliseconds );
 uint32_t b3Hash( uint32_t hash, const uint8_t* data, int count );
 void b3WriteBinaryFile( void* data, int size, const char* fileName );
 void* b3ReadBinaryFile( const char* prefix, const char* fileName, int* memSize );
       
       
typedef struct b3Vec2
{
 float x;
 float y;
} b3Vec2;
typedef struct b3Vec3
{
 float x;
 float y;
 float z;
} b3Vec3;
typedef struct b3CosSin
{
 float cosine;
 float sine;
} b3CosSin;
typedef struct b3Quat
{
 b3Vec3 v;
 float s;
} b3Quat;
typedef struct b3Transform
{
 b3Vec3 p;
 b3Quat q;
} b3Transform;
typedef b3Vec3 b3Pos;
typedef b3Transform b3WorldTransform;
typedef struct b3Matrix3
{
 b3Vec3 cx, cy, cz;
} b3Matrix3;
typedef struct b3AABB
{
 b3Vec3 lowerBound;
 b3Vec3 upperBound;
} b3AABB;
typedef struct b3Plane
{
 b3Vec3 normal;
 float offset;
} b3Plane;
static const b3Vec3 b3Vec3_zero = { 0.0f, 0.0f, 0.0f };
static const b3Vec3 b3Vec3_one = { 1.0f, 1.0f, 1.0f };
static const b3Vec3 b3Vec3_axisX = { 1.0f, 0.0f, 0.0f };
static const b3Vec3 b3Vec3_axisY = { 0.0f, 1.0f, 0.0f };
static const b3Vec3 b3Vec3_axisZ = { 0.0f, 0.0f, 1.0f };
static const b3Quat b3Quat_identity = { { 0.0f, 0.0f, 0.0f }, 1.0f };
static const b3Transform b3Transform_identity = { { 0.0f, 0.0f, 0.0f }, { { 0.0f, 0.0f, 0.0f }, 1.0f } };
static const b3Matrix3 b3Mat3_zero = {
 { 0.0f, 0.0f, 0.0f },
 { 0.0f, 0.0f, 0.0f },
 { 0.0f, 0.0f, 0.0f },
};
static const b3Matrix3 b3Mat3_identity = {
 { 1.0f, 0.0f, 0.0f },
 { 0.0f, 1.0f, 0.0f },
 { 0.0f, 0.0f, 1.0f },
};
static const b3Pos b3Pos_zero = { 0.0f, 0.0f, 0.0f };
static const b3WorldTransform b3WorldTransform_identity = { { 0.0f, 0.0f, 0.0f }, { { 0.0f, 0.0f, 0.0f }, 1.0f } };
 bool b3IsValidFloat( float a );
 float b3Atan2( float y, float x );
 b3CosSin b3ComputeCosSin( float radians );
 b3Quat b3MakeQuatFromMatrix( const b3Matrix3* m );
 b3Quat b3ComputeQuatBetweenUnitVectors( b3Vec3 v1, b3Vec3 v2 );
 b3Matrix3 b3Steiner( float mass, b3Vec3 origin );
typedef struct b3SegmentDistanceResult
{
 b3Vec3 point1;
 float fraction1;
 b3Vec3 point2;
 float fraction2;
} b3SegmentDistanceResult;
 b3Vec3 b3PointToSegmentDistance( b3Vec3 a, b3Vec3 b, b3Vec3 q );
 b3SegmentDistanceResult b3LineDistance( b3Vec3 p1, b3Vec3 d1, b3Vec3 p2, b3Vec3 d2 );
 b3SegmentDistanceResult b3SegmentDistance( b3Vec3 p1, b3Vec3 q1, b3Vec3 p2, b3Vec3 q2 );
 bool b3IsValidVec3( b3Vec3 a );
 bool b3IsValidQuat( b3Quat q );
 bool b3IsValidTransform( b3Transform a );
 bool b3IsValidMatrix3( b3Matrix3 a );
 bool b3IsValidAABB( b3AABB a );
 bool b3IsBoundedAABB( b3AABB a );
 bool b3IsSaneAABB( b3AABB a );
 bool b3IsValidPlane( b3Plane a );
 bool b3IsValidPosition( b3Pos p );
 bool b3IsValidWorldTransform( b3WorldTransform t );
       
       
 void b3SetLengthUnitsPerMeter( float lengthUnits );
 float b3GetLengthUnitsPerMeter( void );
 void b3SetStallThreshold( float seconds );
 float b3GetStallThreshold( void );
       
typedef struct b3WorldId
{
 uint16_t index1;
 uint16_t generation;
} b3WorldId;
typedef struct b3BodyId
{
 int32_t index1;
 uint16_t world0;
 uint16_t generation;
} b3BodyId;
typedef struct b3ShapeId
{
 int32_t index1;
 uint16_t world0;
 uint16_t generation;
} b3ShapeId;
typedef struct b3JointId
{
 int32_t index1;
 uint16_t world0;
 uint16_t generation;
} b3JointId;
typedef struct b3ContactId
{
 int32_t index1;
 uint16_t world0;
 int16_t padding;
 uint32_t generation;
} b3ContactId;
static const b3WorldId b3_nullWorldId = { 0 };
static const b3BodyId b3_nullBodyId = { 0 };
static const b3ShapeId b3_nullShapeId = { 0 };
static const b3JointId b3_nullJointId = { 0 };
static const b3ContactId b3_nullContactId = { 0 };
typedef void b3TaskCallback( void* taskContext );
typedef void* b3EnqueueTaskCallback( b3TaskCallback* task, void* taskContext, void* userContext, const char* taskName );
typedef void b3FinishTaskCallback( void* userTask, void* userContext );
typedef struct b3DebugShape b3DebugShape;
typedef void* b3CreateDebugShapeCallback( const b3DebugShape* debugShape, void* userContext );
typedef void b3DestroyDebugShapeCallback( void* userShape, void* userContext );
typedef float b3FrictionCallback( float frictionA, uint64_t userMaterialIdA, float frictionB, uint64_t userMaterialIdB );
typedef float b3RestitutionCallback( float restitutionA, uint64_t userMaterialIdA, float restitutionB, uint64_t userMaterialIdB );
typedef bool b3CustomFilterFcn( b3ShapeId shapeIdA, b3ShapeId shapeIdB, void* context );
typedef bool b3PreSolveFcn( b3ShapeId shapeIdA, b3ShapeId shapeIdB, b3Pos point, b3Vec3 normal, void* context );
typedef bool b3OverlapResultFcn( b3ShapeId shapeId, void* context );
typedef float b3CastResultFcn( b3ShapeId shapeId, b3Pos point, b3Vec3 normal, float fraction, uint64_t userMaterialId,
          int triangleIndex, int childIndex, void* context );
typedef struct b3Capacity
{
 int staticShapeCount;
 int dynamicShapeCount;
 int staticBodyCount;
 int dynamicBodyCount;
 int contactCount;
} b3Capacity;
typedef struct b3WorldDef
{
 b3Vec3 gravity;
 float restitutionThreshold;
 float hitEventThreshold;
 float contactHertz;
 float contactDampingRatio;
 float contactSpeed;
 float maximumLinearSpeed;
 b3FrictionCallback* frictionCallback;
 b3RestitutionCallback* restitutionCallback;
 bool enableSleep;
 bool enableContinuous;
 uint32_t workerCount;
 b3EnqueueTaskCallback* enqueueTask;
 b3FinishTaskCallback* finishTask;
 void* userTaskContext;
 void* userData;
 b3CreateDebugShapeCallback* createDebugShape;
 b3DestroyDebugShapeCallback* destroyDebugShape;
 void* userDebugShapeContext;
 b3Capacity capacity;
 int internalValue;
} b3WorldDef;
 b3WorldDef b3DefaultWorldDef( void );
typedef enum b3BodyType
{
 b3_staticBody = 0,
 b3_kinematicBody = 1,
 b3_dynamicBody = 2,
 b3_bodyTypeCount,
} b3BodyType;
typedef struct b3MotionLocks
{
 bool linearX;
 bool linearY;
 bool linearZ;
 bool angularX;
 bool angularY;
 bool angularZ;
} b3MotionLocks;
typedef struct b3BodyDef
{
 b3BodyType type;
 b3Pos position;
 b3Quat rotation;
 b3Vec3 linearVelocity;
 b3Vec3 angularVelocity;
 float linearDamping;
 float angularDamping;
 float gravityScale;
 float sleepThreshold;
 const char* name;
 void* userData;
 b3MotionLocks motionLocks;
 bool enableSleep;
 bool isAwake;
 bool isBullet;
 bool isEnabled;
 bool allowFastRotation;
 bool enableContactRecycling;
 int internalValue;
} b3BodyDef;
 b3BodyDef b3DefaultBodyDef( void );
typedef struct b3Filter
{
 uint64_t categoryBits;
 uint64_t maskBits;
 int groupIndex;
} b3Filter;
 b3Filter b3DefaultFilter( void );
typedef struct b3SurfaceMaterial
{
 float friction;
 float restitution;
 float rollingResistance;
 b3Vec3 tangentVelocity;
 uint64_t userMaterialId;
 uint32_t customColor;
} b3SurfaceMaterial;
 b3SurfaceMaterial b3DefaultSurfaceMaterial( void );
typedef enum b3ShapeType
{
 b3_capsuleShape,
 b3_compoundShape,
 b3_heightShape,
 b3_hullShape,
 b3_meshShape,
 b3_sphereShape,
 b3_shapeTypeCount
} b3ShapeType;
typedef struct b3ShapeDef
{
 void* userData;
 b3SurfaceMaterial* materials;
 int materialCount;
 b3SurfaceMaterial baseMaterial;
 float density;
 float explosionScale;
 b3Filter filter;
 bool enableCustomFiltering;
 bool isSensor;
 bool enableSensorEvents;
 bool enableContactEvents;
 bool enableHitEvents;
 bool enablePreSolveEvents;
 bool invokeContactCreation;
 bool updateBodyMass;
 int internalValue;
} b3ShapeDef;
 b3ShapeDef b3DefaultShapeDef( void );
typedef struct b3Profile
{
 float step;
 float pairs;
 float collide;
 float solve;
 float solverSetup;
 float constraints;
 float prepareConstraints;
 float integrateVelocities;
 float warmStart;
 float solveImpulses;
 float integratePositions;
 float relaxImpulses;
 float applyRestitution;
 float storeImpulses;
 float splitIslands;
 float transforms;
 float sensorHits;
 float jointEvents;
 float hitEvents;
 float refit;
 float bullets;
 float sleepIslands;
 float sensors;
} b3Profile;
typedef struct b3Counters
{
 int bodyCount;
 int shapeCount;
 int contactCount;
 int jointCount;
 int islandCount;
 int stackUsed;
 int arenaCapacity;
 int staticTreeHeight;
 int treeHeight;
 int satCallCount;
 int satCacheHitCount;
 int byteCount;
 int taskCount;
 int colorCounts[24];
 int manifoldCounts[8];
 int awakeContactCount;
 int recycledContactCount;
 int distanceIterations;
 int pushBackIterations;
 int rootIterations;
} b3Counters;
typedef enum b3JointType
{
 b3_parallelJoint,
 b3_distanceJoint,
 b3_filterJoint,
 b3_motorJoint,
 b3_prismaticJoint,
 b3_revoluteJoint,
 b3_sphericalJoint,
 b3_weldJoint,
 b3_wheelJoint,
} b3JointType;
typedef struct b3JointDef
{
 void* userData;
 b3BodyId bodyIdA;
 b3BodyId bodyIdB;
 b3Transform localFrameA;
 b3Transform localFrameB;
 float forceThreshold;
 float torqueThreshold;
 float constraintHertz;
 float constraintDampingRatio;
 float drawScale;
 bool collideConnected;
 int internalValue;
} b3JointDef;
typedef struct b3DistanceJointDef
{
 b3JointDef base;
 float length;
 bool enableSpring;
 float lowerSpringForce;
 float upperSpringForce;
 float hertz;
 float dampingRatio;
 bool enableLimit;
 float minLength;
 float maxLength;
 bool enableMotor;
 float maxMotorForce;
 float motorSpeed;
} b3DistanceJointDef;
 b3DistanceJointDef b3DefaultDistanceJointDef( void );
typedef struct b3MotorJointDef
{
 b3JointDef base;
 b3Vec3 linearVelocity;
 float maxVelocityForce;
 b3Vec3 angularVelocity;
 float maxVelocityTorque;
 float linearHertz;
 float linearDampingRatio;
 float maxSpringForce;
 float angularHertz;
 float angularDampingRatio;
 float maxSpringTorque;
} b3MotorJointDef;
 b3MotorJointDef b3DefaultMotorJointDef( void );
typedef struct b3FilterJointDef
{
 b3JointDef base;
} b3FilterJointDef;
 b3FilterJointDef b3DefaultFilterJointDef( void );
typedef struct b3ParallelJointDef
{
 b3JointDef base;
 float hertz;
 float dampingRatio;
 float maxTorque;
} b3ParallelJointDef;
 b3ParallelJointDef b3DefaultParallelJointDef( void );
typedef struct b3PrismaticJointDef
{
 b3JointDef base;
 bool enableSpring;
 float hertz;
 float dampingRatio;
 float targetTranslation;
 bool enableLimit;
 float lowerTranslation;
 float upperTranslation;
 bool enableMotor;
 float maxMotorForce;
 float motorSpeed;
} b3PrismaticJointDef;
 b3PrismaticJointDef b3DefaultPrismaticJointDef( void );
typedef struct b3RevoluteJointDef
{
 b3JointDef base;
 float targetAngle;
 bool enableSpring;
 float hertz;
 float dampingRatio;
 bool enableLimit;
 float lowerAngle;
 float upperAngle;
 bool enableMotor;
 float maxMotorTorque;
 float motorSpeed;
} b3RevoluteJointDef;
 b3RevoluteJointDef b3DefaultRevoluteJointDef( void );
typedef struct b3SphericalJointDef
{
 b3JointDef base;
 bool enableSpring;
 float hertz;
 float dampingRatio;
 b3Quat targetRotation;
 bool enableConeLimit;
 float coneAngle;
 bool enableTwistLimit;
 float lowerTwistAngle;
 float upperTwistAngle;
 bool enableMotor;
 float maxMotorTorque;
 b3Vec3 motorVelocity;
} b3SphericalJointDef;
 b3SphericalJointDef b3DefaultSphericalJointDef( void );
typedef struct b3WeldJointDef
{
 b3JointDef base;
 float linearHertz;
 float angularHertz;
 float linearDampingRatio;
 float angularDampingRatio;
} b3WeldJointDef;
 b3WeldJointDef b3DefaultWeldJointDef( void );
typedef struct b3WheelJointDef
{
 b3JointDef base;
 bool enableSuspensionSpring;
 float suspensionHertz;
 float suspensionDampingRatio;
 bool enableSuspensionLimit;
 float lowerSuspensionLimit;
 float upperSuspensionLimit;
 bool enableSpinMotor;
 float maxSpinTorque;
 float spinSpeed;
 bool enableSteering;
 float steeringHertz;
 float steeringDampingRatio;
 float targetSteeringAngle;
 float maxSteeringTorque;
 bool enableSteeringLimit;
 float lowerSteeringLimit;
 float upperSteeringLimit;
} b3WheelJointDef;
 b3WheelJointDef b3DefaultWheelJointDef( void );
typedef struct b3ExplosionDef
{
 uint64_t maskBits;
 b3Pos position;
 float radius;
 float falloff;
 float impulsePerArea;
} b3ExplosionDef;
 b3ExplosionDef b3DefaultExplosionDef( void );
typedef struct b3SensorBeginTouchEvent
{
 b3ShapeId sensorShapeId;
 b3ShapeId visitorShapeId;
} b3SensorBeginTouchEvent;
typedef struct b3SensorEndTouchEvent
{
 b3ShapeId sensorShapeId;
 b3ShapeId visitorShapeId;
} b3SensorEndTouchEvent;
typedef struct b3SensorEvents
{
 b3SensorBeginTouchEvent* beginEvents;
 b3SensorEndTouchEvent* endEvents;
 int beginCount;
 int endCount;
} b3SensorEvents;
typedef struct b3ContactBeginTouchEvent
{
 b3ShapeId shapeIdA;
 b3ShapeId shapeIdB;
 b3ContactId contactId;
} b3ContactBeginTouchEvent;
typedef struct b3ContactEndTouchEvent
{
 b3ShapeId shapeIdA;
 b3ShapeId shapeIdB;
 b3ContactId contactId;
} b3ContactEndTouchEvent;
typedef struct b3ContactHitEvent
{
 b3ShapeId shapeIdA;
 b3ShapeId shapeIdB;
 b3ContactId contactId;
 b3Pos point;
 b3Vec3 normal;
 float approachSpeed;
 uint64_t userMaterialIdA;
 uint64_t userMaterialIdB;
} b3ContactHitEvent;
typedef struct b3ContactEvents
{
 b3ContactBeginTouchEvent* beginEvents;
 b3ContactEndTouchEvent* endEvents;
 b3ContactHitEvent* hitEvents;
 int beginCount;
 int endCount;
 int hitCount;
} b3ContactEvents;
typedef struct b3BodyMoveEvent
{
 void* userData;
 b3WorldTransform transform;
 b3BodyId bodyId;
 bool fellAsleep;
} b3BodyMoveEvent;
typedef struct b3BodyEvents
{
 b3BodyMoveEvent* moveEvents;
 int moveCount;
} b3BodyEvents;
typedef struct b3JointEvent
{
 b3JointId jointId;
 void* userData;
} b3JointEvent;
typedef struct b3JointEvents
{
 b3JointEvent* jointEvents;
 int count;
} b3JointEvents;
typedef struct b3ContactData
{
 b3ContactId contactId;
 b3ShapeId shapeIdA;
 b3ShapeId shapeIdB;
 const struct b3Manifold* manifolds;
 int manifoldCount;
} b3ContactData;
typedef struct b3QueryFilter
{
 uint64_t categoryBits;
 uint64_t maskBits;
 uint64_t id;
 const char* name;
} b3QueryFilter;
 b3QueryFilter b3DefaultQueryFilter( void );
typedef struct b3RayCastInput
{
 b3Vec3 origin;
 b3Vec3 translation;
 float maxFraction;
} b3RayCastInput;
typedef struct b3RayResult
{
 b3ShapeId shapeId;
 b3Pos point;
 b3Vec3 normal;
 uint64_t userMaterialId;
 float fraction;
 int triangleIndex;
 int childIndex;
 int nodeVisits;
 int leafVisits;
 bool hit;
} b3RayResult;
typedef struct b3ShapeProxy
{
 const b3Vec3* points;
 int count;
 float radius;
} b3ShapeProxy;
typedef struct b3ShapeCastInput
{
 b3ShapeProxy proxy;
 b3Vec3 translation;
 float maxFraction;
 bool canEncroach;
} b3ShapeCastInput;
typedef struct b3BoxCastInput
{
 b3AABB box;
 b3Vec3 translation;
 float maxFraction;
} b3BoxCastInput;
typedef struct b3CastOutput
{
 b3Vec3 normal;
 b3Vec3 point;
 float fraction;
 int iterations;
 int triangleIndex;
 int childIndex;
 int materialIndex;
 bool hit;
} b3CastOutput;
typedef b3CastOutput b3WorldCastOutput;
typedef struct b3BodyCastResult
{
 b3ShapeId shapeId;
 b3Pos point;
 b3Vec3 normal;
 float fraction;
 int triangleIndex;
 uint64_t userMaterialId;
 int iterations;
 bool hit;
} b3BodyCastResult;
typedef struct b3SimplexCache
{
 float metric;
 uint16_t count;
 uint8_t indexA[4];
 uint8_t indexB[4];
} b3SimplexCache;
static const b3SimplexCache b3_emptyDistanceCache = {0};
typedef struct b3ShapeCastPairInput
{
 b3ShapeProxy proxyA;
 b3ShapeProxy proxyB;
 b3Transform transform;
 b3Vec3 translationB;
 float maxFraction;
 bool canEncroach;
} b3ShapeCastPairInput;
typedef struct b3DistanceInput
{
 b3ShapeProxy proxyA;
 b3ShapeProxy proxyB;
 b3Transform transform;
 bool useRadii;
} b3DistanceInput;
typedef struct b3DistanceOutput
{
 b3Vec3 pointA;
 b3Vec3 pointB;
 b3Vec3 normal;
 float distance;
 int iterations;
 int simplexCount;
} b3DistanceOutput;
typedef struct b3SimplexVertex
{
 b3Vec3 wA;
 b3Vec3 wB;
 b3Vec3 w;
 float a;
 int indexA;
 int indexB;
} b3SimplexVertex;
typedef struct b3Simplex
{
 b3SimplexVertex vertices[4];
 int count;
} b3Simplex;
typedef struct b3Sweep
{
 b3Vec3 localCenter;
 b3Vec3 c1;
 b3Vec3 c2;
 b3Quat q1;
 b3Quat q2;
} b3Sweep;
typedef struct b3TOIInput
{
 b3ShapeProxy proxyA;
 b3ShapeProxy proxyB;
 b3Sweep sweepA;
 b3Sweep sweepB;
 float maxFraction;
} b3TOIInput;
typedef enum b3TOIState
{
 b3_toiStateUnknown,
 b3_toiStateFailed,
 b3_toiStateOverlapped,
 b3_toiStateHit,
 b3_toiStateSeparated
} b3TOIState;
typedef struct b3TOIOutput
{
 b3TOIState state;
 b3Vec3 point;
 b3Vec3 normal;
 float fraction;
 float distance;
 int distanceIterations;
 int pushBackIterations;
 int rootIterations;
 bool usedFallback;
} b3TOIOutput;
typedef enum b3TreeNodeFlags
{
 b3_allocatedNode = 0x0001,
 b3_enlargedNode = 0x0002,
 b3_leafNode = 0x0004,
} b3TreeNodeFlags;
typedef struct b3TreeNodeChildren
{
 int child1;
 int child2;
} b3TreeNodeChildren;
typedef struct b3TreeNode
{
 b3AABB aabb;
 uint64_t categoryBits;
 union
 {
  b3TreeNodeChildren children;
  uint64_t userData;
 };
 union
 {
  int parent;
  int next;
 };
 uint16_t height;
 uint16_t flags;
} b3TreeNode;
typedef struct b3DynamicTree
{
 uint64_t version;
 b3TreeNode* nodes;
 int root;
 int nodeCount;
 int nodeCapacity;
 int proxyCount;
 int freeList;
 int* leafIndices;
 b3AABB* leafBoxes;
 b3Vec3* leafCenters;
 int* binIndices;
 int rebuildCapacity;
} b3DynamicTree;
typedef struct b3TreeStats
{
 int nodeVisits;
 int leafVisits;
} b3TreeStats;
typedef bool b3TreeQueryCallbackFcn( int proxyId, uint64_t userData, void* context );
typedef float b3TreeQueryClosestCallbackFcn( float distanceSqrMin, int proxyId, uint64_t userData, void* context );
typedef float b3TreeBoxCastCallbackFcn( const b3BoxCastInput* input, int proxyId, uint64_t userData, void* context );
typedef float b3TreeRayCastCallbackFcn( const b3RayCastInput* input, int proxyId, uint64_t userData, void* context );
typedef struct b3PlaneResult
{
 b3Plane plane;
 b3Vec3 point;
} b3PlaneResult;
typedef struct b3CollisionPlane
{
 b3Plane plane;
 float pushLimit;
 float push;
 bool clipVelocity;
} b3CollisionPlane;
typedef struct b3PlaneSolverResult
{
 b3Vec3 delta;
 int iterationCount;
} b3PlaneSolverResult;
typedef struct b3BodyPlaneResult
{
 b3ShapeId shapeId;
 b3PlaneResult result;
} b3BodyPlaneResult;
typedef bool b3PlaneResultFcn( b3ShapeId shapeId, const b3PlaneResult* plane, int planeCount, void* context );
typedef bool b3MoverFilterFcn( b3ShapeId shapeId, void* context );
typedef struct b3MassData
{
 float mass;
 b3Vec3 center;
 b3Matrix3 inertia;
} b3MassData;
typedef struct b3Sphere
{
 b3Vec3 center;
 float radius;
} b3Sphere;
typedef struct b3Capsule
{
 b3Vec3 center1;
 b3Vec3 center2;
 float radius;
} b3Capsule;
typedef struct b3HullVertex
{
 uint8_t edge;
} b3HullVertex;
typedef struct b3HullHalfEdge
{
 uint8_t next;
 uint8_t twin;
 uint8_t origin;
 uint8_t face;
} b3HullHalfEdge;
typedef struct b3HullFace
{
 uint8_t edge;
} b3HullFace;
typedef struct b3HullData
{
 uint64_t version;
 int byteCount;
 uint32_t hash;
 b3AABB aabb;
 float surfaceArea;
 float volume;
 float innerRadius;
 b3Vec3 center;
 b3Matrix3 centralInertia;
 int vertexCount;
 int vertexOffset;
 int pointOffset;
 int edgeCount;
 int edgeOffset;
 int faceCount;
 int faceOffset;
 int planeOffset;
 int padding;
} b3HullData;
typedef struct b3BoxHull
{
 b3HullData base;
 b3HullVertex boxVertices[8];
 b3Vec3 boxPoints[8];
 b3HullHalfEdge boxEdges[24];
 b3HullFace boxFaces[6];
 uint8_t padding[2];
 b3Plane boxPlanes[6];
} b3BoxHull;
typedef struct b3MeshDef
{
 b3Vec3* vertices;
 int32_t* indices;
 uint8_t* materialIndices;
 float weldTolerance;
 int vertexCount;
 int triangleCount;
 bool weldVertices;
 bool useMedianSplit;
 bool identifyEdges;
} b3MeshDef;
typedef enum b3MeshEdgeFlags
{
 b3_concaveEdge1 = 0x01,
 b3_concaveEdge2 = 0x02,
 b3_concaveEdge3 = 0x04,
 b3_inverseConcaveEdge1 = 0x10,
 b3_inverseConcaveEdge2 = 0x20,
 b3_inverseConcaveEdge3 = 0x40,
 b3_allConcaveEdges = b3_concaveEdge1 | b3_concaveEdge2 | b3_concaveEdge3,
 b3_flatEdge1 = b3_concaveEdge1 | b3_inverseConcaveEdge1,
 b3_flatEdge2 = b3_concaveEdge2 | b3_inverseConcaveEdge2,
 b3_flatEdge3 = b3_concaveEdge3 | b3_inverseConcaveEdge3,
 b3_allFlatEdges = b3_flatEdge1 | b3_flatEdge2 | b3_flatEdge3,
} b3MeshEdgeFlags;
typedef struct b3MeshTriangle
{
 int32_t index1;
 int32_t index2;
 int32_t index3;
} b3MeshTriangle;
typedef struct b3MeshNode
{
 b3Vec3 lowerBound;
 union
 {
  struct
  {
   uint32_t axis : 2;
   uint32_t childOffset : 30;
  } asNode;
  struct
  {
   uint32_t type : 2;
   uint32_t triangleCount : 30;
  } asLeaf;
 } data;
 b3Vec3 upperBound;
 uint32_t triangleOffset;
} b3MeshNode;
typedef struct b3MeshData
{
 uint64_t version;
 int byteCount;
 uint32_t hash;
 b3AABB bounds;
 float surfaceArea;
 int treeHeight;
 int degenerateCount;
 int nodeOffset;
 int nodeCount;
 int vertexOffset;
 int vertexCount;
 int triangleOffset;
 int triangleCount;
 int materialOffset;
 int materialCount;
 int flagsOffset;
} b3MeshData;
typedef struct b3Mesh
{
 const b3MeshData* data;
 b3Vec3 scale;
} b3Mesh;
typedef struct b3HeightFieldDef
{
 float* heights;
 uint8_t* materialIndices;
 b3Vec3 scale;
 int countX;
 int countZ;
 float globalMinimumHeight;
 float globalMaximumHeight;
 bool clockwiseWinding;
} b3HeightFieldDef;
typedef struct b3HeightFieldData
{
 uint64_t version;
 int byteCount;
 uint32_t hash;
 b3AABB aabb;
 float minHeight;
 float maxHeight;
 float heightScale;
 b3Vec3 scale;
 int columnCount;
 int rowCount;
 int heightsOffset;
 int materialOffset;
 int flagsOffset;
 bool clockwise;
 uint8_t padding[3];
} b3HeightFieldData;
typedef struct b3CompoundCapsuleDef
{
 b3Capsule capsule;
 b3SurfaceMaterial material;
} b3CompoundCapsuleDef;
typedef struct b3CompoundHullDef
{
 const b3HullData* hull;
 b3Transform transform;
 b3SurfaceMaterial material;
} b3CompoundHullDef;
typedef struct b3CompoundMeshDef
{
 const b3MeshData* meshData;
 b3Transform transform;
 b3Vec3 scale;
 const b3SurfaceMaterial* materials;
 int materialCount;
} b3CompoundMeshDef;
typedef struct b3CompoundSphereDef
{
 b3Sphere sphere;
 b3SurfaceMaterial material;
} b3CompoundSphereDef;
typedef struct b3CompoundDef
{
 b3CompoundCapsuleDef* capsules;
 int capsuleCount;
 b3CompoundHullDef* hulls;
 int hullCount;
 b3CompoundMeshDef* meshes;
 int meshCount;
 b3CompoundSphereDef* spheres;
 int sphereCount;
} b3CompoundDef;
typedef struct b3CompoundData
{
 uint64_t version;
 int byteCount;
 int nodeOffset;
 b3DynamicTree tree;
 int materialOffset;
 int materialCount;
 int capsuleOffset;
 int capsuleCount;
 int hullOffset;
 int hullCount;
 int sharedHullCount;
 int meshOffset;
 int meshCount;
 int sharedMeshCount;
 int sphereOffset;
 int sphereCount;
} b3CompoundData;
typedef struct b3CompoundCapsule
{
 b3Capsule capsule;
 int materialIndex;
} b3CompoundCapsule;
typedef struct b3CompoundHull
{
 const b3HullData* hull;
 b3Transform transform;
 int materialIndex;
} b3CompoundHull;
typedef struct b3CompoundMesh
{
 const b3MeshData* meshData;
 b3Transform transform;
 b3Vec3 scale;
 int materialIndices[4];
} b3CompoundMesh;
typedef struct b3CompoundSphere
{
 b3Sphere sphere;
 int materialIndex;
} b3CompoundSphere;
typedef struct b3ChildShape
{
 union
 {
  b3Capsule capsule;
  const b3HullData* hull;
  b3Mesh mesh;
  b3Sphere sphere;
 };
 b3Transform transform;
 int materialIndices[4];
 b3ShapeType type;
} b3ChildShape;
typedef bool b3CompoundQueryFcn( const b3CompoundData* compound, int childIndex, void* context );
typedef struct b3ManifoldPoint
{
 b3Vec3 anchorA;
 b3Vec3 anchorB;
 float separation;
 float baseSeparation;
 float normalImpulse;
 float totalNormalImpulse;
 float normalVelocity;
 uint32_t featureId;
 int triangleIndex;
 bool persisted;
} b3ManifoldPoint;
typedef struct b3Manifold
{
 b3ManifoldPoint points[4];
 b3Vec3 normal;
 float twistImpulse;
 b3Vec3 frictionImpulse;
 b3Vec3 rollingImpulse;
 int pointCount;
} b3Manifold;
typedef enum
{
 b3_invalidAxis = 0,
 b3_backsideAxis,
 b3_faceAxisA,
 b3_faceAxisB,
 b3_edgePairAxis,
 b3_closestPointsAxis,
 b3_manualFaceAxisA,
 b3_manualFaceAxisB,
 b3_manualEdgePairAxis,
} b3SeparatingFeature;
typedef enum
{
 b3_featureNone = 0,
 b3_featureTriangleFace,
 b3_featureHullFace,
 b3_featureEdge1,
 b3_featureEdge2,
 b3_featureEdge3,
 b3_featureVertex1,
 b3_featureVertex2,
 b3_featureVertex3
} b3TriangleFeature;
typedef struct
{
 float separation;
 uint8_t type;
 uint8_t indexA;
 uint8_t indexB;
 uint8_t hit;
} b3SATCache;
typedef struct b3FeaturePair
{
 uint8_t owner1;
 uint8_t index1;
 uint8_t owner2;
 uint8_t index2;
} b3FeaturePair;
typedef struct b3LocalManifoldPoint
{
 b3Vec3 point;
 float separation;
 b3FeaturePair pair;
 int triangleIndex;
} b3LocalManifoldPoint;
typedef struct b3LocalManifold
{
 b3Vec3 normal;
 b3Vec3 triangleNormal;
 b3LocalManifoldPoint* points;
 int pointCount;
 int triangleIndex;
 int i1;
 int i2;
 int i3;
 float squaredDistance;
 b3TriangleFeature feature;
 int triangleFlags;
} b3LocalManifold;
typedef enum b3HexColor
{
 b3_colorAliceBlue = 0xF0F8FF,
 b3_colorAntiqueWhite = 0xFAEBD7,
 b3_colorAqua = 0x00FFFF,
 b3_colorAquamarine = 0x7FFFD4,
 b3_colorAzure = 0xF0FFFF,
 b3_colorBeige = 0xF5F5DC,
 b3_colorBisque = 0xFFE4C4,
 b3_colorBlack = 0x000000,
 b3_colorBlanchedAlmond = 0xFFEBCD,
 b3_colorBlue = 0x0000FF,
 b3_colorBlueViolet = 0x8A2BE2,
 b3_colorBrown = 0xA52A2A,
 b3_colorBurlywood = 0xDEB887,
 b3_colorCadetBlue = 0x5F9EA0,
 b3_colorChartreuse = 0x7FFF00,
 b3_colorChocolate = 0xD2691E,
 b3_colorCoral = 0xFF7F50,
 b3_colorCornflowerBlue = 0x6495ED,
 b3_colorCornsilk = 0xFFF8DC,
 b3_colorCrimson = 0xDC143C,
 b3_colorCyan = 0x00FFFF,
 b3_colorDarkBlue = 0x00008B,
 b3_colorDarkCyan = 0x008B8B,
 b3_colorDarkGoldenRod = 0xB8860B,
 b3_colorDarkGray = 0xA9A9A9,
 b3_colorDarkGreen = 0x006400,
 b3_colorDarkKhaki = 0xBDB76B,
 b3_colorDarkMagenta = 0x8B008B,
 b3_colorDarkOliveGreen = 0x556B2F,
 b3_colorDarkOrange = 0xFF8C00,
 b3_colorDarkOrchid = 0x9932CC,
 b3_colorDarkRed = 0x8B0000,
 b3_colorDarkSalmon = 0xE9967A,
 b3_colorDarkSeaGreen = 0x8FBC8F,
 b3_colorDarkSlateBlue = 0x483D8B,
 b3_colorDarkSlateGray = 0x2F4F4F,
 b3_colorDarkTurquoise = 0x00CED1,
 b3_colorDarkViolet = 0x9400D3,
 b3_colorDeepPink = 0xFF1493,
 b3_colorDeepSkyBlue = 0x00BFFF,
 b3_colorDimGray = 0x696969,
 b3_colorDodgerBlue = 0x1E90FF,
 b3_colorFireBrick = 0xB22222,
 b3_colorFloralWhite = 0xFFFAF0,
 b3_colorForestGreen = 0x228B22,
 b3_colorFuchsia = 0xFF00FF,
 b3_colorGainsboro = 0xDCDCDC,
 b3_colorGhostWhite = 0xF8F8FF,
 b3_colorGold = 0xFFD700,
 b3_colorGoldenRod = 0xDAA520,
 b3_colorGray = 0x808080,
 b3_colorGreen = 0x008000,
 b3_colorGreenYellow = 0xADFF2F,
 b3_colorHoneyDew = 0xF0FFF0,
 b3_colorHotPink = 0xFF69B4,
 b3_colorIndianRed = 0xCD5C5C,
 b3_colorIndigo = 0x4B0082,
 b3_colorIvory = 0xFFFFF0,
 b3_colorKhaki = 0xF0E68C,
 b3_colorLavender = 0xE6E6FA,
 b3_colorLavenderBlush = 0xFFF0F5,
 b3_colorLawnGreen = 0x7CFC00,
 b3_colorLemonChiffon = 0xFFFACD,
 b3_colorLightBlue = 0xADD8E6,
 b3_colorLightCoral = 0xF08080,
 b3_colorLightCyan = 0xE0FFFF,
 b3_colorLightGoldenRodYellow = 0xFAFAD2,
 b3_colorLightGray = 0xD3D3D3,
 b3_colorLightGreen = 0x90EE90,
 b3_colorLightPink = 0xFFB6C1,
 b3_colorLightSalmon = 0xFFA07A,
 b3_colorLightSeaGreen = 0x20B2AA,
 b3_colorLightSkyBlue = 0x87CEFA,
 b3_colorLightSlateGray = 0x778899,
 b3_colorLightSteelBlue = 0xB0C4DE,
 b3_colorLightYellow = 0xFFFFE0,
 b3_colorLime = 0x00FF00,
 b3_colorLimeGreen = 0x32CD32,
 b3_colorLinen = 0xFAF0E6,
 b3_colorMagenta = 0xFF00FF,
 b3_colorMaroon = 0x800000,
 b3_colorMediumAquaMarine = 0x66CDAA,
 b3_colorMediumBlue = 0x0000CD,
 b3_colorMediumOrchid = 0xBA55D3,
 b3_colorMediumPurple = 0x9370DB,
 b3_colorMediumSeaGreen = 0x3CB371,
 b3_colorMediumSlateBlue = 0x7B68EE,
 b3_colorMediumSpringGreen = 0x00FA9A,
 b3_colorMediumTurquoise = 0x48D1CC,
 b3_colorMediumVioletRed = 0xC71585,
 b3_colorMidnightBlue = 0x191970,
 b3_colorMintCream = 0xF5FFFA,
 b3_colorMistyRose = 0xFFE4E1,
 b3_colorMoccasin = 0xFFE4B5,
 b3_colorNavajoWhite = 0xFFDEAD,
 b3_colorNavy = 0x000080,
 b3_colorOldLace = 0xFDF5E6,
 b3_colorOlive = 0x808000,
 b3_colorOliveDrab = 0x6B8E23,
 b3_colorOrange = 0xFFA500,
 b3_colorOrangeRed = 0xFF4500,
 b3_colorOrchid = 0xDA70D6,
 b3_colorPaleGoldenRod = 0xEEE8AA,
 b3_colorPaleGreen = 0x98FB98,
 b3_colorPaleTurquoise = 0xAFEEEE,
 b3_colorPaleVioletRed = 0xDB7093,
 b3_colorPapayaWhip = 0xFFEFD5,
 b3_colorPeachPuff = 0xFFDAB9,
 b3_colorPeru = 0xCD853F,
 b3_colorPink = 0xFFC0CB,
 b3_colorPlum = 0xDDA0DD,
 b3_colorPowderBlue = 0xB0E0E6,
 b3_colorPurple = 0x800080,
 b3_colorRebeccaPurple = 0x663399,
 b3_colorRed = 0xFF0000,
 b3_colorRosyBrown = 0xBC8F8F,
 b3_colorRoyalBlue = 0x4169E1,
 b3_colorSaddleBrown = 0x8B4513,
 b3_colorSalmon = 0xFA8072,
 b3_colorSandyBrown = 0xF4A460,
 b3_colorSeaGreen = 0x2E8B57,
 b3_colorSeaShell = 0xFFF5EE,
 b3_colorSienna = 0xA0522D,
 b3_colorSilver = 0xC0C0C0,
 b3_colorSkyBlue = 0x87CEEB,
 b3_colorSlateBlue = 0x6A5ACD,
 b3_colorSlateGray = 0x708090,
 b3_colorSnow = 0xFFFAFA,
 b3_colorSpringGreen = 0x00FF7F,
 b3_colorSteelBlue = 0x4682B4,
 b3_colorTan = 0xD2B48C,
 b3_colorTeal = 0x008080,
 b3_colorThistle = 0xD8BFD8,
 b3_colorTomato = 0xFF6347,
 b3_colorTurquoise = 0x40E0D0,
 b3_colorViolet = 0xEE82EE,
 b3_colorWheat = 0xF5DEB3,
 b3_colorWhite = 0xFFFFFF,
 b3_colorWhiteSmoke = 0xF5F5F5,
 b3_colorYellow = 0xFFFF00,
 b3_colorYellowGreen = 0x9ACD32,
 b3_colorBox2DRed = 0xDC3132,
 b3_colorBox2DBlue = 0x30AEBF,
 b3_colorBox2DGreen = 0x8CC924,
 b3_colorBox2DYellow = 0xFFEE8C
} b3HexColor;
typedef enum b3DebugMaterial
{
 b3_debugMaterialDefault = 0,
 b3_debugMaterialMatte,
 b3_debugMaterialSoft,
 b3_debugMaterialDead,
 b3_debugMaterialGlossy,
 b3_debugMaterialMetallic
} b3DebugMaterial;
 b3HexColor b3GetGraphColor( int index );
typedef struct b3DebugShape
{
 b3ShapeId shapeId;
 b3ShapeType type;
 union
 {
  const b3Capsule* capsule;
  const b3CompoundData* compound;
  const b3HeightFieldData* heightField;
  const b3HullData* hull;
  const b3Mesh* mesh;
  const b3Sphere* sphere;
 };
} b3DebugShape;
typedef struct b3DebugDraw
{
 bool ( *DrawShapeFcn )( void* userShape, b3WorldTransform transform, b3HexColor color, void* context );
 void ( *DrawSegmentFcn )( b3Pos p1, b3Pos p2, b3HexColor color, void* context );
 void ( *DrawTransformFcn )( b3WorldTransform transform, void* context );
 void ( *DrawPointFcn )( b3Pos p, float size, b3HexColor color, void* context );
 void ( *DrawSphereFcn )( b3Pos p, float radius, b3HexColor color, float alpha, void* context );
 void ( *DrawCapsuleFcn )( b3Pos p1, b3Pos p2, float radius, b3HexColor color, float alpha, void* context );
 void ( *DrawBoundsFcn )( b3AABB aabb, b3HexColor color, void* context );
 void ( *DrawBoxFcn )( b3Vec3 extents, b3WorldTransform transform, b3HexColor color, void* context );
 void ( *DrawStringFcn )( b3Pos p, const char* s, b3HexColor color, void* context );
 b3AABB drawingBounds;
 float forceScale;
 float jointScale;
 bool drawShapes;
 bool drawJoints;
 bool drawJointExtras;
 bool drawBounds;
 bool drawMass;
 bool drawBodyNames;
 bool drawContacts;
 int drawAnchorA;
 bool drawGraphColors;
 bool drawContactFeatures;
 bool drawContactNormals;
 bool drawContactForces;
 bool drawFrictionForces;
 bool drawIslands;
 void* context;
} b3DebugDraw;
 b3DebugDraw b3DefaultDebugDraw( void );
 b3DynamicTree b3DynamicTree_Create( int proxyCapacity );
 void b3DynamicTree_Destroy( b3DynamicTree* tree );
 int b3DynamicTree_CreateProxy( b3DynamicTree* tree, b3AABB aabb, uint64_t categoryBits, uint64_t userData );
 void b3DynamicTree_DestroyProxy( b3DynamicTree* tree, int proxyId );
 void b3DynamicTree_MoveProxy( b3DynamicTree* tree, int proxyId, b3AABB aabb );
 void b3DynamicTree_EnlargeProxy( b3DynamicTree* tree, int proxyId, b3AABB aabb );
 void b3DynamicTree_SetCategoryBits( b3DynamicTree* tree, int proxyId, uint64_t categoryBits );
 uint64_t b3DynamicTree_GetCategoryBits( b3DynamicTree* tree, int proxyId );
 b3TreeStats b3DynamicTree_Query( const b3DynamicTree* tree, b3AABB aabb, uint64_t maskBits, bool requireAllBits,
          b3TreeQueryCallbackFcn* callback, void* context );
 b3TreeStats b3DynamicTree_QueryClosest( const b3DynamicTree* tree, b3Vec3 point, uint64_t maskBits, bool requireAllBits,
              b3TreeQueryClosestCallbackFcn* callback, void* context, float* minDistanceSqr );
 b3TreeStats b3DynamicTree_RayCast( const b3DynamicTree* tree, const b3RayCastInput* input, uint64_t maskBits,
            bool requireAllBits, b3TreeRayCastCallbackFcn* callback, void* context );
 b3TreeStats b3DynamicTree_BoxCast( const b3DynamicTree* tree, const b3BoxCastInput* input, uint64_t maskBits,
            bool requireAllBits, b3TreeBoxCastCallbackFcn* callback, void* context );
 void b3DynamicTree_Validate( const b3DynamicTree* tree );
 int b3DynamicTree_GetHeight( const b3DynamicTree* tree );
 float b3DynamicTree_GetAreaRatio( const b3DynamicTree* tree );
 b3AABB b3DynamicTree_GetRootBounds( const b3DynamicTree* tree );
 int b3DynamicTree_GetProxyCount( const b3DynamicTree* tree );
 int b3DynamicTree_Rebuild( b3DynamicTree* tree, bool fullBuild );
 int b3DynamicTree_GetByteCount( const b3DynamicTree* tree );
 void b3DynamicTree_ValidateNoEnlarged( const b3DynamicTree* tree );
 void b3DynamicTree_Save( const b3DynamicTree* tree, const char* fileName );
 b3DynamicTree b3DynamicTree_Load( const char* fileName, float scale );
 b3HullData* b3CreateCylinder( float height, float radius, float yOffset, int sides );
 b3HullData* b3CreateCone( float height, float radius1, float radius2, int slices );
 b3HullData* b3CreateRock( float radius );
 b3HullData* b3CreateHull( const b3Vec3* points, int pointCount, int maxVertexCount );
 b3HullData* b3CloneHull( const b3HullData* hull );
 b3HullData* b3CloneAndTransformHull( const b3HullData* original, b3Transform transform, b3Vec3 scale );
 void b3DestroyHull( b3HullData* hull );
 b3BoxHull b3MakeCubeHull( float halfWidth );
 b3BoxHull b3MakeBoxHull( float hx, float hy, float hz );
 b3BoxHull b3MakeOffsetBoxHull( float hx, float hy, float hz, b3Vec3 offset );
 b3BoxHull b3MakeTransformedBoxHull( float hx, float hy, float hz, b3Transform transform );
 b3BoxHull b3MakeScaledBoxHull( b3Vec3 halfWidths, b3Transform transform, b3Vec3 postScale );
 void b3ScaleBox( b3Vec3* halfWidths, b3Transform* transform, b3Vec3 postScale, float minHalfWidth );
 b3MeshData* b3CreateGridMesh( int xCount, int zCount, float cellWidth, int materialCount, bool identifyEdges );
 b3MeshData* b3CreateWaveMesh( int xCount, int zCount, float cellWidth, float amplitude, float rowFrequency,
          float columnFrequency );
 b3MeshData* b3CreateTorusMesh( int radialResolution, int tubularResolution, float radius, float thickness );
 b3MeshData* b3CreateBoxMesh( b3Vec3 center, b3Vec3 extent, bool identifyEdges );
 b3MeshData* b3CreateHollowBoxMesh( b3Vec3 center, b3Vec3 extent );
 b3MeshData* b3CreatePlatformMesh( b3Vec3 center, float height, float topWidth, float bottomWidth );
 b3MeshData* b3CreateMesh( const b3MeshDef* def, int* degenerateTriangleIndices, int degenerateCapacity );
 void b3DestroyMesh( b3MeshData* mesh );
 int b3GetHeight( const b3MeshData* mesh );
 b3HeightFieldData* b3CreateHeightField( const b3HeightFieldDef* data );
 b3HeightFieldData* b3CreateGrid( int rowCount, int columnCount, b3Vec3 scale, bool makeHoles );
 b3HeightFieldData* b3CreateWave( int rowCount, int columnCount, b3Vec3 scale, float rowFrequency, float columnFrequency,
          bool makeHoles );
 void b3DestroyHeightField( b3HeightFieldData* heightField );
 void b3DumpHeightData( const b3HeightFieldDef* data, const char* fileName );
 b3HeightFieldData* b3LoadHeightField( const char* fileName );
 b3ChildShape b3GetCompoundChild( const b3CompoundData* compound, int childIndex );
 void b3QueryCompound( const b3CompoundData* compound, b3AABB aabb, b3CompoundQueryFcn* fcn, void* context );
 b3CompoundCapsule b3GetCompoundCapsule( const b3CompoundData* compound, int index );
 b3CompoundHull b3GetCompoundHull( const b3CompoundData* compound, int index );
 b3CompoundMesh b3GetCompoundMesh( const b3CompoundData* compound, int index );
 b3CompoundSphere b3GetCompoundSphere( const b3CompoundData* compound, int index );
 const b3SurfaceMaterial* b3GetCompoundMaterials( const b3CompoundData* compound );
 b3CompoundData* b3CreateCompound( const b3CompoundDef* def );
 void b3DestroyCompound( b3CompoundData* compound );
 uint8_t* b3ConvertCompoundToBytes( b3CompoundData* compound );
 b3CompoundData* b3ConvertBytesToCompound( uint8_t* bytes, int byteCount );
 b3MassData b3ComputeSphereMass( const b3Sphere* shape, float density );
 b3MassData b3ComputeCapsuleMass( const b3Capsule* shape, float density );
 b3MassData b3ComputeHullMass( const b3HullData* shape, float density );
 b3AABB b3ComputeSphereAABB( const b3Sphere* shape, b3Transform transform );
 b3AABB b3ComputeCapsuleAABB( const b3Capsule* shape, b3Transform transform );
 b3AABB b3ComputeHullAABB( const b3HullData* shape, b3Transform transform );
 b3AABB b3ComputeMeshAABB( const b3MeshData* shape, b3Transform transform, b3Vec3 scale );
 b3AABB b3ComputeHeightFieldAABB( const b3HeightFieldData* shape, b3Transform transform );
 b3AABB b3ComputeCompoundAABB( const b3CompoundData* shape, b3Transform transform );
 bool b3IsValidRay( const b3RayCastInput* input );
 bool b3OverlapCapsule( const b3Capsule* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 bool b3OverlapCompound( const b3CompoundData* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 bool b3OverlapHeightField( const b3HeightFieldData* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 bool b3OverlapHull( const b3HullData* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 bool b3OverlapMesh( const b3Mesh* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 bool b3OverlapSphere( const b3Sphere* shape, b3Transform shapeTransform, const b3ShapeProxy* proxy );
 b3CastOutput b3RayCastSphere( const b3Sphere* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastHollowSphere( const b3Sphere* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastCapsule( const b3Capsule* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastCompound( const b3CompoundData* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastHull( const b3HullData* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastMesh( const b3Mesh* shape, const b3RayCastInput* input );
 b3CastOutput b3RayCastHeightField( const b3HeightFieldData* shape, const b3RayCastInput* input );
 b3CastOutput b3ShapeCastSphere( const b3Sphere* shape, const b3ShapeCastInput* input );
 b3CastOutput b3ShapeCastCapsule( const b3Capsule* shape, const b3ShapeCastInput* input );
 b3CastOutput b3ShapeCastCompound( const b3CompoundData* shape, const b3ShapeCastInput* input );
 b3CastOutput b3ShapeCastHull( const b3HullData* shape, const b3ShapeCastInput* input );
 b3CastOutput b3ShapeCastMesh( const b3Mesh* shape, const b3ShapeCastInput* input );
 b3CastOutput b3ShapeCastHeightField( const b3HeightFieldData* shape, const b3ShapeCastInput* input );
typedef bool b3MeshQueryFcn( b3Vec3 a, b3Vec3 b, b3Vec3 c, int triangleIndex, void* context );
 void b3QueryMesh( const b3Mesh* mesh, const b3AABB bounds, b3MeshQueryFcn* fcn, void* context );
 void b3QueryHeightField( const b3HeightFieldData* heightField, b3AABB bounds, b3MeshQueryFcn* fcn, void* context );
 b3DistanceOutput b3ShapeDistance( const b3DistanceInput* input, b3SimplexCache* cache, b3Simplex* simplexes,
           int simplexCapacity );
 b3CastOutput b3ShapeCast( const b3ShapeCastPairInput* input );
 b3Transform b3GetSweepTransform( const b3Sweep* sweep, float time );
 b3TOIOutput b3TimeOfImpact( const b3TOIInput* input );
 void b3CollideSpheres( b3LocalManifold* manifold, int capacity, const b3Sphere* sphereA, const b3Sphere* sphereB,
         b3Transform transformBtoA );
 void b3CollideCapsuleAndSphere( b3LocalManifold* manifold, int capacity, const b3Capsule* capsuleA,
            const b3Sphere* sphereB, b3Transform transformBtoA );
 void b3CollideHullAndSphere( b3LocalManifold* manifold, int capacity, const b3HullData* hullA, const b3Sphere* sphereB,
         b3Transform transformBtoA, b3SimplexCache* cache );
 void b3CollideCapsules( b3LocalManifold* manifold, int capacity, const b3Capsule* capsuleA, const b3Capsule* capsuleB,
          b3Transform transformBtoA );
 void b3CollideHullAndCapsule( b3LocalManifold* manifold, int capacity, const b3HullData* hullA, const b3Capsule* capsuleB,
          b3Transform transformBtoA, b3SimplexCache* cache );
 void b3CollideHulls( b3LocalManifold* manifold, int capacity, const b3HullData* hullA, const b3HullData* hullB,
       b3Transform transformBtoA, b3SATCache* cache );
 void b3CollideCapsuleAndTriangle( b3LocalManifold* manifold, int capacity, const b3Capsule* capsuleA,
           const b3Vec3* triangleB, b3SimplexCache* cache );
 void b3CollideHullAndTriangle( b3LocalManifold* manifold, int capacity, const b3HullData* hullA, b3Vec3 v1, b3Vec3 v2,
           b3Vec3 v3, int triangleFlags, b3SATCache* cache );
 void b3CollideSphereAndTriangle( b3LocalManifold* manifold, int capacity, const b3Sphere* sphereA,
          const b3Vec3* triangleB );
 b3PlaneSolverResult b3SolvePlanes( b3Vec3 targetDelta, b3CollisionPlane* planes, int count );
 b3Vec3 b3ClipVector( b3Vec3 vector, const b3CollisionPlane* planes, int count );
 b3WorldId b3CreateWorld( const b3WorldDef* def );
 void b3DestroyWorld( b3WorldId worldId );
 int b3GetWorldCount( void );
 int b3GetMaxWorldCount( void );
 bool b3World_IsValid( b3WorldId id );
 void b3World_Step( b3WorldId worldId, float timeStep, int subStepCount );
 void b3World_Draw( b3WorldId worldId, b3DebugDraw* draw, uint64_t maskBits );
 b3AABB b3World_GetBounds( b3WorldId worldId );
 b3BodyEvents b3World_GetBodyEvents( b3WorldId worldId );
 b3SensorEvents b3World_GetSensorEvents( b3WorldId worldId );
 b3ContactEvents b3World_GetContactEvents( b3WorldId worldId );
 b3JointEvents b3World_GetJointEvents( b3WorldId worldId );
 b3TreeStats b3World_OverlapAABB( b3WorldId worldId, b3AABB aabb, b3QueryFilter filter, b3OverlapResultFcn* fcn,
          void* context );
 b3TreeStats b3World_OverlapShape( b3WorldId worldId, b3Pos origin, const b3ShapeProxy* proxy, b3QueryFilter filter,
           b3OverlapResultFcn* fcn, void* context );
 b3TreeStats b3World_CastRay( b3WorldId worldId, b3Pos origin, b3Vec3 translation, b3QueryFilter filter,
         b3CastResultFcn* fcn, void* context );
 b3RayResult b3World_CastRayClosest( b3WorldId worldId, b3Pos origin, b3Vec3 translation, b3QueryFilter filter );
 b3TreeStats b3World_CastShape( b3WorldId worldId, b3Pos origin, const b3ShapeProxy* proxy, b3Vec3 translation,
           b3QueryFilter filter, b3CastResultFcn* fcn, void* context );
 float b3World_CastMover( b3WorldId worldId, b3Pos origin, const b3Capsule* mover, b3Vec3 translation, b3QueryFilter filter,
        b3MoverFilterFcn* fcn, void* context );
 void b3World_CollideMover( b3WorldId worldId, b3Pos origin, const b3Capsule* mover, b3QueryFilter filter,
          b3PlaneResultFcn* fcn, void* context );
 void b3World_EnableSleeping( b3WorldId worldId, bool flag );
 bool b3World_IsSleepingEnabled( b3WorldId worldId );
 void b3World_EnableContinuous( b3WorldId worldId, bool flag );
 bool b3World_IsContinuousEnabled( b3WorldId worldId );
 void b3World_SetRestitutionThreshold( b3WorldId worldId, float value );
 float b3World_GetRestitutionThreshold( b3WorldId worldId );
 void b3World_SetHitEventThreshold( b3WorldId worldId, float value );
 float b3World_GetHitEventThreshold( b3WorldId worldId );
 void b3World_SetCustomFilterCallback( b3WorldId worldId, b3CustomFilterFcn* fcn, void* context );
 void b3World_SetPreSolveCallback( b3WorldId worldId, b3PreSolveFcn* fcn, void* context );
 void b3World_SetGravity( b3WorldId worldId, b3Vec3 gravity );
 b3Vec3 b3World_GetGravity( b3WorldId worldId );
 void b3World_Explode( b3WorldId worldId, const b3ExplosionDef* explosionDef );
 void b3World_SetContactTuning( b3WorldId worldId, float hertz, float dampingRatio, float contactSpeed );
 void b3World_SetContactRecycleDistance( b3WorldId worldId, float recycleDistance );
 float b3World_GetContactRecycleDistance( b3WorldId worldId );
 void b3World_SetMaximumLinearSpeed( b3WorldId worldId, float maximumLinearSpeed );
 float b3World_GetMaximumLinearSpeed( b3WorldId worldId );
 void b3World_EnableWarmStarting( b3WorldId worldId, bool flag );
 bool b3World_IsWarmStartingEnabled( b3WorldId worldId );
 int b3World_GetAwakeBodyCount( b3WorldId worldId );
 b3Profile b3World_GetProfile( b3WorldId worldId );
 b3Counters b3World_GetCounters( b3WorldId worldId );
 b3Capacity b3World_GetMaxCapacity( b3WorldId worldId );
 void b3World_SetUserData( b3WorldId worldId, void* userData );
 void* b3World_GetUserData( b3WorldId worldId );
 void b3World_SetFrictionCallback( b3WorldId worldId, b3FrictionCallback* callback );
 void b3World_SetRestitutionCallback( b3WorldId worldId, b3RestitutionCallback* callback );
 void b3World_SetWorkerCount( b3WorldId worldId, int count );
 int b3World_GetWorkerCount( b3WorldId worldId );
 void b3World_DumpMemoryStats( b3WorldId worldId );
 void b3World_DumpShapeBounds( b3WorldId worldId, b3BodyType type );
 void b3World_RebuildStaticTree( b3WorldId worldId );
 void b3World_EnableSpeculative( b3WorldId worldId, bool flag );
 void b3World_DumpAwake( b3WorldId worldId );
 void b3World_Dump( b3WorldId worldId );
typedef struct b3Recording b3Recording;
 b3Recording* b3CreateRecording( int byteCapacity );
 void b3DestroyRecording( b3Recording* recording );
 const uint8_t* b3Recording_GetData( const b3Recording* recording );
 int b3Recording_GetSize( const b3Recording* recording );
 void b3World_StartRecording( b3WorldId worldId, b3Recording* recording );
 void b3World_StopRecording( b3WorldId worldId );
 bool b3SaveRecordingToFile( const b3Recording* recording, const char* path );
 b3Recording* b3LoadRecordingFromFile( const char* path );
 bool b3ValidateReplay( const void* data, int size, int workerCount );
typedef struct b3RecPlayer b3RecPlayer;
typedef struct b3RecPlayerInfo
{
 int frameCount;
 int workerCount;
 float timeStep;
 int subStepCount;
 float lengthScale;
 b3AABB bounds;
} b3RecPlayerInfo;
 b3RecPlayer* b3RecPlayer_Create( const void* data, int size, int workerCount );
 void b3RecPlayer_Destroy( b3RecPlayer* player );
 bool b3RecPlayer_StepFrame( b3RecPlayer* player );
 void b3RecPlayer_Restart( b3RecPlayer* player );
 void b3RecPlayer_SeekFrame( b3RecPlayer* player, int targetFrame );
 b3WorldId b3RecPlayer_GetWorldId( const b3RecPlayer* player );
 int b3RecPlayer_GetFrame( const b3RecPlayer* player );
 int b3RecPlayer_GetFrameCount( const b3RecPlayer* player );
 bool b3RecPlayer_IsAtEnd( const b3RecPlayer* player );
 bool b3RecPlayer_HasDiverged( const b3RecPlayer* player );
 b3RecPlayerInfo b3RecPlayer_GetInfo( const b3RecPlayer* player );
 int b3RecPlayer_GetDivergeFrame( const b3RecPlayer* player );
 void b3RecPlayer_SetWorkerCount( b3RecPlayer* player, int count );
 void b3RecPlayer_SetKeyframePolicy( b3RecPlayer* player, size_t budgetBytes, int minIntervalFrames );
 size_t b3RecPlayer_GetKeyframeBudget( const b3RecPlayer* player );
 int b3RecPlayer_GetKeyframeMinInterval( const b3RecPlayer* player );
 int b3RecPlayer_GetKeyframeInterval( const b3RecPlayer* player );
 size_t b3RecPlayer_GetKeyframeBytes( const b3RecPlayer* player );
 int b3RecPlayer_GetBodyCount( const b3RecPlayer* player );
 b3BodyId b3RecPlayer_GetBodyId( const b3RecPlayer* player, int index );
 void b3RecPlayer_SetDebugShapeCallbacks( b3RecPlayer* player, b3CreateDebugShapeCallback* createDebugShape,
                                                b3DestroyDebugShapeCallback* destroyDebugShape, void* context );
 void b3RecPlayer_DrawFrameQueries( b3RecPlayer* player, b3DebugDraw* draw, int queryIndex, int selectedIndex );
typedef enum b3RecQueryType
{
 b3_recQueryOverlapAABB,
 b3_recQueryOverlapShape,
 b3_recQueryCastRay,
 b3_recQueryCastShape,
 b3_recQueryCastRayClosest,
 b3_recQueryCastMover,
 b3_recQueryCollideMover,
} b3RecQueryType;
typedef struct b3RecQueryInfo
{
 b3RecQueryType type;
 b3QueryFilter filter;
 b3AABB aabb;
 b3Pos origin;
 b3Vec3 translation;
 int hitCount;
 uint64_t key;
 uint64_t id;
 const char* name;
} b3RecQueryInfo;
typedef struct b3RecQueryHit
{
 b3ShapeId shape;
 b3Pos point;
 b3Vec3 normal;
 float fraction;
} b3RecQueryHit;
 int b3RecPlayer_GetFrameQueryCount( const b3RecPlayer* player );
 b3RecQueryInfo b3RecPlayer_GetFrameQuery( const b3RecPlayer* player, int index );
 b3RecQueryHit b3RecPlayer_GetFrameQueryHit( const b3RecPlayer* player, int queryIndex, int hitIndex );
 b3BodyId b3CreateBody( b3WorldId worldId, const b3BodyDef* def );
 void b3DestroyBody( b3BodyId bodyId );
 bool b3Body_IsValid( b3BodyId id );
 b3BodyType b3Body_GetType( b3BodyId bodyId );
 void b3Body_SetType( b3BodyId bodyId, b3BodyType type );
 void b3Body_SetName( b3BodyId bodyId, const char* name );
 const char* b3Body_GetName( b3BodyId bodyId );
 void b3Body_SetUserData( b3BodyId bodyId, void* userData );
 void* b3Body_GetUserData( b3BodyId bodyId );
 b3Pos b3Body_GetPosition( b3BodyId bodyId );
 b3Quat b3Body_GetRotation( b3BodyId bodyId );
 b3WorldTransform b3Body_GetTransform( b3BodyId bodyId );
 void b3Body_SetTransform( b3BodyId bodyId, b3Pos position, b3Quat rotation );
 b3Vec3 b3Body_GetLocalPoint( b3BodyId bodyId, b3Pos worldPoint );
 b3Pos b3Body_GetWorldPoint( b3BodyId bodyId, b3Vec3 localPoint );
 b3Vec3 b3Body_GetLocalVector( b3BodyId bodyId, b3Vec3 worldVector );
 b3Vec3 b3Body_GetWorldVector( b3BodyId bodyId, b3Vec3 localVector );
 b3Vec3 b3Body_GetLinearVelocity( b3BodyId bodyId );
 b3Vec3 b3Body_GetAngularVelocity( b3BodyId bodyId );
 void b3Body_SetLinearVelocity( b3BodyId bodyId, b3Vec3 linearVelocity );
 void b3Body_SetAngularVelocity( b3BodyId bodyId, b3Vec3 angularVelocity );
 void b3Body_SetTargetTransform( b3BodyId bodyId, b3WorldTransform target, float timeStep, bool wake );
 b3Vec3 b3Body_GetLocalPointVelocity( b3BodyId bodyId, b3Vec3 localPoint );
 b3Vec3 b3Body_GetWorldPointVelocity( b3BodyId bodyId, b3Pos worldPoint );
 void b3Body_ApplyForce( b3BodyId bodyId, b3Vec3 force, b3Pos point, bool wake );
 void b3Body_ApplyForceToCenter( b3BodyId bodyId, b3Vec3 force, bool wake );
 void b3Body_ApplyTorque( b3BodyId bodyId, b3Vec3 torque, bool wake );
 void b3Body_ApplyLinearImpulse( b3BodyId bodyId, b3Vec3 impulse, b3Pos point, bool wake );
 void b3Body_ApplyLinearImpulseToCenter( b3BodyId bodyId, b3Vec3 impulse, bool wake );
 void b3Body_ApplyAngularImpulse( b3BodyId bodyId, b3Vec3 impulse, bool wake );
 float b3Body_GetMass( b3BodyId bodyId );
 b3Matrix3 b3Body_GetLocalRotationalInertia( b3BodyId bodyId );
 float b3Body_GetInverseMass( b3BodyId bodyId );
 b3Matrix3 b3Body_GetWorldInverseRotationalInertia( b3BodyId bodyId );
 b3Vec3 b3Body_GetLocalCenterOfMass( b3BodyId bodyId );
 b3Pos b3Body_GetWorldCenterOfMass( b3BodyId bodyId );
 void b3Body_SetMassData( b3BodyId bodyId, b3MassData massData );
 b3MassData b3Body_GetMassData( b3BodyId bodyId );
 void b3Body_ApplyMassFromShapes( b3BodyId bodyId );
 void b3Body_SetLinearDamping( b3BodyId bodyId, float linearDamping );
 float b3Body_GetLinearDamping( b3BodyId bodyId );
 void b3Body_SetAngularDamping( b3BodyId bodyId, float angularDamping );
 float b3Body_GetAngularDamping( b3BodyId bodyId );
 void b3Body_SetGravityScale( b3BodyId bodyId, float gravityScale );
 float b3Body_GetGravityScale( b3BodyId bodyId );
 bool b3Body_IsAwake( b3BodyId bodyId );
 void b3Body_SetAwake( b3BodyId bodyId, bool awake );
 void b3Body_EnableSleep( b3BodyId bodyId, bool enableSleep );
 bool b3Body_IsSleepEnabled( b3BodyId bodyId );
 void b3Body_SetSleepThreshold( b3BodyId bodyId, float sleepThreshold );
 float b3Body_GetSleepThreshold( b3BodyId bodyId );
 bool b3Body_IsEnabled( b3BodyId bodyId );
 void b3Body_Disable( b3BodyId bodyId );
 void b3Body_Enable( b3BodyId bodyId );
 void b3Body_SetMotionLocks( b3BodyId bodyId, b3MotionLocks locks );
 b3MotionLocks b3Body_GetMotionLocks( b3BodyId bodyId );
 void b3Body_SetBullet( b3BodyId bodyId, bool flag );
 bool b3Body_IsBullet( b3BodyId bodyId );
 void b3Body_EnableContactRecycling( b3BodyId bodyId, bool flag );
 bool b3Body_IsContactRecyclingEnabled( b3BodyId bodyId );
 void b3Body_EnableHitEvents( b3BodyId bodyId, bool enableHitEvents );
 b3WorldId b3Body_GetWorld( b3BodyId bodyId );
 int b3Body_GetShapeCount( b3BodyId bodyId );
 int b3Body_GetShapes( b3BodyId bodyId, b3ShapeId* shapeArray, int capacity );
 int b3Body_GetJointCount( b3BodyId bodyId );
 int b3Body_GetJoints( b3BodyId bodyId, b3JointId* jointArray, int capacity );
 int b3Body_GetContactCapacity( b3BodyId bodyId );
 int b3Body_GetContactData( b3BodyId bodyId, b3ContactData* contactData, int capacity );
 b3AABB b3Body_ComputeAABB( b3BodyId bodyId );
 float b3Body_GetClosestPoint( b3BodyId bodyId, b3Vec3* result, b3Vec3 target );
 b3BodyCastResult b3Body_CastRay( b3BodyId bodyId, b3Pos origin, b3Vec3 translation, b3QueryFilter filter,
          float maxFraction, b3WorldTransform bodyTransform );
 b3BodyCastResult b3Body_CastShape( b3BodyId bodyId, b3Pos origin, const b3ShapeProxy* proxy, b3Vec3 translation,
            b3QueryFilter filter, float maxFraction, bool canEncroach,
            b3WorldTransform bodyTransform );
 bool b3Body_OverlapShape( b3BodyId bodyId, b3Pos origin, const b3ShapeProxy* proxy, b3QueryFilter filter,
         b3WorldTransform bodyTransform );
 int b3Body_CollideMover( b3BodyId bodyId, b3BodyPlaneResult* bodyPlanes, int planeCapacity, b3Pos origin, const b3Capsule* mover,
        b3QueryFilter filter, b3WorldTransform bodyTransform );
 b3ShapeId b3CreateSphereShape( b3BodyId bodyId, const b3ShapeDef* def, const b3Sphere* sphere );
 b3ShapeId b3CreateCapsuleShape( b3BodyId bodyId, const b3ShapeDef* def, const b3Capsule* capsule );
 b3ShapeId b3CreateHullShape( b3BodyId bodyId, const b3ShapeDef* def, const b3HullData* hull );
 b3ShapeId b3CreateTransformedHullShape( b3BodyId bodyId, const b3ShapeDef* def, const b3HullData* hull,
              b3Transform transform, b3Vec3 scale );
 b3ShapeId b3CreateMeshShape( b3BodyId bodyId, const b3ShapeDef* def, const b3MeshData* mesh, b3Vec3 scale );
 b3ShapeId b3CreateHeightFieldShape( b3BodyId bodyId, const b3ShapeDef* def, const b3HeightFieldData* heightField );
 b3ShapeId b3CreateCompoundShape( b3BodyId bodyId, b3ShapeDef* def, const b3CompoundData* compound );
 void b3DestroyShape( b3ShapeId shapeId, bool updateBodyMass );
 bool b3Shape_IsValid( b3ShapeId id );
 b3ShapeType b3Shape_GetType( b3ShapeId shapeId );
 b3BodyId b3Shape_GetBody( b3ShapeId shapeId );
 b3WorldId b3Shape_GetWorld( b3ShapeId shapeId );
 bool b3Shape_IsSensor( b3ShapeId shapeId );
 void b3Shape_SetUserData( b3ShapeId shapeId, void* userData );
 void* b3Shape_GetUserData( b3ShapeId shapeId );
 void b3Shape_SetDensity( b3ShapeId shapeId, float density, bool updateBodyMass );
 float b3Shape_GetDensity( b3ShapeId shapeId );
 void b3Shape_SetFriction( b3ShapeId shapeId, float friction );
 float b3Shape_GetFriction( b3ShapeId shapeId );
 void b3Shape_SetRestitution( b3ShapeId shapeId, float restitution );
 float b3Shape_GetRestitution( b3ShapeId shapeId );
 void b3Shape_SetSurfaceMaterial( b3ShapeId shapeId, b3SurfaceMaterial surfaceMaterial );
 b3SurfaceMaterial b3Shape_GetSurfaceMaterial( b3ShapeId shapeId );
 int b3Shape_GetMeshMaterialCount( b3ShapeId shapeId );
 void b3Shape_SetMeshMaterial( b3ShapeId shapeId, b3SurfaceMaterial surfaceMaterial, int index );
 b3SurfaceMaterial b3Shape_GetMeshSurfaceMaterial( b3ShapeId shapeId, int index );
 b3Filter b3Shape_GetFilter( b3ShapeId shapeId );
 void b3Shape_SetFilter( b3ShapeId shapeId, b3Filter filter, bool invokeContacts );
 void b3Shape_EnableSensorEvents( b3ShapeId shapeId, bool flag );
 bool b3Shape_AreSensorEventsEnabled( b3ShapeId shapeId );
 void b3Shape_EnableContactEvents( b3ShapeId shapeId, bool flag );
 bool b3Shape_AreContactEventsEnabled( b3ShapeId shapeId );
 void b3Shape_EnablePreSolveEvents( b3ShapeId shapeId, bool flag );
 bool b3Shape_ArePreSolveEventsEnabled( b3ShapeId shapeId );
 void b3Shape_EnableHitEvents( b3ShapeId shapeId, bool flag );
 bool b3Shape_AreHitEventsEnabled( b3ShapeId shapeId );
 b3WorldCastOutput b3Shape_RayCast( b3ShapeId shapeId, b3Pos origin, b3Vec3 translation );
 b3Sphere b3Shape_GetSphere( b3ShapeId shapeId );
 b3Capsule b3Shape_GetCapsule( b3ShapeId shapeId );
 const b3HullData* b3Shape_GetHull( b3ShapeId shapeId );
 b3Mesh b3Shape_GetMesh( b3ShapeId shapeId );
 const b3HeightFieldData* b3Shape_GetHeightField( b3ShapeId shapeId );
 void b3Shape_SetSphere( b3ShapeId shapeId, const b3Sphere* sphere );
 void b3Shape_SetCapsule( b3ShapeId shapeId, const b3Capsule* capsule );
 void b3Shape_SetHull( b3ShapeId shapeId, const b3HullData* hull );
 void b3Shape_SetMesh( b3ShapeId shapeId, const b3MeshData* meshData, b3Vec3 scale );
 int b3Shape_GetContactCapacity( b3ShapeId shapeId );
 int b3Shape_GetContactData( b3ShapeId shapeId, b3ContactData* contactData, int capacity );
 int b3Shape_GetSensorCapacity( b3ShapeId shapeId );
 int b3Shape_GetSensorData( b3ShapeId shapeId, b3ShapeId* visitorIds, int capacity );
 b3AABB b3Shape_GetAABB( b3ShapeId shapeId );
 b3MassData b3Shape_ComputeMassData( b3ShapeId shapeId );
 b3Vec3 b3Shape_GetClosestPoint( b3ShapeId shapeId, b3Vec3 target );
 void b3Shape_ApplyWind( b3ShapeId shapeId, b3Vec3 wind, float drag, float lift, float maxSpeed, bool wake );
 void b3DestroyJoint( b3JointId jointId, bool wakeAttached );
 bool b3Joint_IsValid( b3JointId id );
 b3JointType b3Joint_GetType( b3JointId jointId );
 b3BodyId b3Joint_GetBodyA( b3JointId jointId );
 b3BodyId b3Joint_GetBodyB( b3JointId jointId );
 b3WorldId b3Joint_GetWorld( b3JointId jointId );
 void b3Joint_SetLocalFrameA( b3JointId jointId, b3Transform localFrame );
 b3Transform b3Joint_GetLocalFrameA( b3JointId jointId );
 void b3Joint_SetLocalFrameB( b3JointId jointId, b3Transform localFrame );
 b3Transform b3Joint_GetLocalFrameB( b3JointId jointId );
 void b3Joint_SetCollideConnected( b3JointId jointId, bool shouldCollide );
 bool b3Joint_GetCollideConnected( b3JointId jointId );
 void b3Joint_SetUserData( b3JointId jointId, void* userData );
 void* b3Joint_GetUserData( b3JointId jointId );
 void b3Joint_WakeBodies( b3JointId jointId );
 b3Vec3 b3Joint_GetConstraintForce( b3JointId jointId );
 b3Vec3 b3Joint_GetConstraintTorque( b3JointId jointId );
 float b3Joint_GetLinearSeparation( b3JointId jointId );
 float b3Joint_GetAngularSeparation( b3JointId jointId );
 void b3Joint_SetConstraintTuning( b3JointId jointId, float hertz, float dampingRatio );
 void b3Joint_GetConstraintTuning( b3JointId jointId, float* hertz, float* dampingRatio );
 void b3Joint_SetForceThreshold( b3JointId jointId, float threshold );
 float b3Joint_GetForceThreshold( b3JointId jointId );
 void b3Joint_SetTorqueThreshold( b3JointId jointId, float threshold );
 float b3Joint_GetTorqueThreshold( b3JointId jointId );
 b3JointId b3CreateParallelJoint( b3WorldId worldId, const b3ParallelJointDef* def );
 void b3ParallelJoint_SetSpringHertz( b3JointId jointId, float hertz );
 void b3ParallelJoint_SetSpringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3ParallelJoint_GetSpringHertz( b3JointId jointId );
 float b3ParallelJoint_GetSpringDampingRatio( b3JointId jointId );
 void b3ParallelJoint_SetMaxTorque( b3JointId jointId, float force );
 float b3ParallelJoint_GetMaxTorque( b3JointId jointId );
 b3JointId b3CreateDistanceJoint( b3WorldId worldId, const b3DistanceJointDef* def );
 void b3DistanceJoint_SetLength( b3JointId jointId, float length );
 float b3DistanceJoint_GetLength( b3JointId jointId );
 void b3DistanceJoint_EnableSpring( b3JointId jointId, bool enableSpring );
 bool b3DistanceJoint_IsSpringEnabled( b3JointId jointId );
 void b3DistanceJoint_SetSpringForceRange( b3JointId jointId, float lowerForce, float upperForce );
 void b3DistanceJoint_GetSpringForceRange( b3JointId jointId, float* lowerForce, float* upperForce );
 void b3DistanceJoint_SetSpringHertz( b3JointId jointId, float hertz );
 void b3DistanceJoint_SetSpringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3DistanceJoint_GetSpringHertz( b3JointId jointId );
 float b3DistanceJoint_GetSpringDampingRatio( b3JointId jointId );
 void b3DistanceJoint_EnableLimit( b3JointId jointId, bool enableLimit );
 bool b3DistanceJoint_IsLimitEnabled( b3JointId jointId );
 void b3DistanceJoint_SetLengthRange( b3JointId jointId, float minLength, float maxLength );
 float b3DistanceJoint_GetMinLength( b3JointId jointId );
 float b3DistanceJoint_GetMaxLength( b3JointId jointId );
 float b3DistanceJoint_GetCurrentLength( b3JointId jointId );
 void b3DistanceJoint_EnableMotor( b3JointId jointId, bool enableMotor );
 bool b3DistanceJoint_IsMotorEnabled( b3JointId jointId );
 void b3DistanceJoint_SetMotorSpeed( b3JointId jointId, float motorSpeed );
 float b3DistanceJoint_GetMotorSpeed( b3JointId jointId );
 void b3DistanceJoint_SetMaxMotorForce( b3JointId jointId, float force );
 float b3DistanceJoint_GetMaxMotorForce( b3JointId jointId );
 float b3DistanceJoint_GetMotorForce( b3JointId jointId );
 b3JointId b3CreateMotorJoint( b3WorldId worldId, const b3MotorJointDef* def );
 void b3MotorJoint_SetLinearVelocity( b3JointId jointId, b3Vec3 velocity );
 b3Vec3 b3MotorJoint_GetLinearVelocity( b3JointId jointId );
 void b3MotorJoint_SetAngularVelocity( b3JointId jointId, b3Vec3 velocity );
 b3Vec3 b3MotorJoint_GetAngularVelocity( b3JointId jointId );
 void b3MotorJoint_SetMaxVelocityForce( b3JointId jointId, float maxForce );
 float b3MotorJoint_GetMaxVelocityForce( b3JointId jointId );
 void b3MotorJoint_SetMaxVelocityTorque( b3JointId jointId, float maxTorque );
 float b3MotorJoint_GetMaxVelocityTorque( b3JointId jointId );
 void b3MotorJoint_SetLinearHertz( b3JointId jointId, float hertz );
 float b3MotorJoint_GetLinearHertz( b3JointId jointId );
 void b3MotorJoint_SetLinearDampingRatio( b3JointId jointId, float damping );
 float b3MotorJoint_GetLinearDampingRatio( b3JointId jointId );
 void b3MotorJoint_SetAngularHertz( b3JointId jointId, float hertz );
 float b3MotorJoint_GetAngularHertz( b3JointId jointId );
 void b3MotorJoint_SetAngularDampingRatio( b3JointId jointId, float damping );
 float b3MotorJoint_GetAngularDampingRatio( b3JointId jointId );
 void b3MotorJoint_SetMaxSpringForce( b3JointId jointId, float maxForce );
 float b3MotorJoint_GetMaxSpringForce( b3JointId jointId );
 void b3MotorJoint_SetMaxSpringTorque( b3JointId jointId, float maxTorque );
 float b3MotorJoint_GetMaxSpringTorque( b3JointId jointId );
 b3JointId b3CreateFilterJoint( b3WorldId worldId, const b3FilterJointDef* def );
 b3JointId b3CreatePrismaticJoint( b3WorldId worldId, const b3PrismaticJointDef* def );
 void b3PrismaticJoint_EnableSpring( b3JointId jointId, bool enableSpring );
 bool b3PrismaticJoint_IsSpringEnabled( b3JointId jointId );
 void b3PrismaticJoint_SetSpringHertz( b3JointId jointId, float hertz );
 float b3PrismaticJoint_GetSpringHertz( b3JointId jointId );
 void b3PrismaticJoint_SetSpringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3PrismaticJoint_GetSpringDampingRatio( b3JointId jointId );
 void b3PrismaticJoint_SetTargetTranslation( b3JointId jointId, float targetTranslation );
 float b3PrismaticJoint_GetTargetTranslation( b3JointId jointId );
 void b3PrismaticJoint_EnableLimit( b3JointId jointId, bool enableLimit );
 bool b3PrismaticJoint_IsLimitEnabled( b3JointId jointId );
 float b3PrismaticJoint_GetLowerLimit( b3JointId jointId );
 float b3PrismaticJoint_GetUpperLimit( b3JointId jointId );
 void b3PrismaticJoint_SetLimits( b3JointId jointId, float lower, float upper );
 void b3PrismaticJoint_EnableMotor( b3JointId jointId, bool enableMotor );
 bool b3PrismaticJoint_IsMotorEnabled( b3JointId jointId );
 void b3PrismaticJoint_SetMotorSpeed( b3JointId jointId, float motorSpeed );
 float b3PrismaticJoint_GetMotorSpeed( b3JointId jointId );
 void b3PrismaticJoint_SetMaxMotorForce( b3JointId jointId, float force );
 float b3PrismaticJoint_GetMaxMotorForce( b3JointId jointId );
 float b3PrismaticJoint_GetMotorForce( b3JointId jointId );
 float b3PrismaticJoint_GetTranslation( b3JointId jointId );
 float b3PrismaticJoint_GetSpeed( b3JointId jointId );
 b3JointId b3CreateRevoluteJoint( b3WorldId worldId, const b3RevoluteJointDef* def );
 void b3RevoluteJoint_EnableSpring( b3JointId jointId, bool enableSpring );
 bool b3RevoluteJoint_IsSpringEnabled( b3JointId jointId );
 void b3RevoluteJoint_SetSpringHertz( b3JointId jointId, float hertz );
 float b3RevoluteJoint_GetSpringHertz( b3JointId jointId );
 void b3RevoluteJoint_SetSpringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3RevoluteJoint_GetSpringDampingRatio( b3JointId jointId );
 void b3RevoluteJoint_SetTargetAngle( b3JointId jointId, float targetRadians );
 float b3RevoluteJoint_GetTargetAngle( b3JointId jointId );
 float b3RevoluteJoint_GetAngle( b3JointId jointId );
 void b3RevoluteJoint_EnableLimit( b3JointId jointId, bool enableLimit );
 bool b3RevoluteJoint_IsLimitEnabled( b3JointId jointId );
 float b3RevoluteJoint_GetLowerLimit( b3JointId jointId );
 float b3RevoluteJoint_GetUpperLimit( b3JointId jointId );
 void b3RevoluteJoint_SetLimits( b3JointId jointId, float lowerLimitRadians, float upperLimitRadians );
 void b3RevoluteJoint_EnableMotor( b3JointId jointId, bool enableMotor );
 bool b3RevoluteJoint_IsMotorEnabled( b3JointId jointId );
 void b3RevoluteJoint_SetMotorSpeed( b3JointId jointId, float motorSpeed );
 float b3RevoluteJoint_GetMotorSpeed( b3JointId jointId );
 float b3RevoluteJoint_GetMotorTorque( b3JointId jointId );
 void b3RevoluteJoint_SetMaxMotorTorque( b3JointId jointId, float torque );
 float b3RevoluteJoint_GetMaxMotorTorque( b3JointId jointId );
 b3JointId b3CreateSphericalJoint( b3WorldId worldId, const b3SphericalJointDef* def );
 void b3SphericalJoint_EnableConeLimit( b3JointId jointId, bool enableLimit );
 bool b3SphericalJoint_IsConeLimitEnabled( b3JointId jointId );
 float b3SphericalJoint_GetConeLimit( b3JointId jointId );
 void b3SphericalJoint_SetConeLimit( b3JointId jointId, float angleRadians );
 float b3SphericalJoint_GetConeAngle( b3JointId jointId );
 void b3SphericalJoint_EnableTwistLimit( b3JointId jointId, bool enableLimit );
 bool b3SphericalJoint_IsTwistLimitEnabled( b3JointId jointId );
 float b3SphericalJoint_GetLowerTwistLimit( b3JointId jointId );
 float b3SphericalJoint_GetUpperTwistLimit( b3JointId jointId );
 void b3SphericalJoint_SetTwistLimits( b3JointId jointId, float lowerLimitRadians, float upperLimitRadians );
 float b3SphericalJoint_GetTwistAngle( b3JointId jointId );
 void b3SphericalJoint_EnableSpring( b3JointId jointId, bool enableSpring );
 bool b3SphericalJoint_IsSpringEnabled( b3JointId jointId );
 void b3SphericalJoint_SetSpringHertz( b3JointId jointId, float hertz );
 float b3SphericalJoint_GetSpringHertz( b3JointId jointId );
 void b3SphericalJoint_SetSpringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3SphericalJoint_GetSpringDampingRatio( b3JointId jointId );
 void b3SphericalJoint_SetTargetRotation( b3JointId jointId, b3Quat targetRotation );
 b3Quat b3SphericalJoint_GetTargetRotation( b3JointId jointId );
 void b3SphericalJoint_EnableMotor( b3JointId jointId, bool enableMotor );
 bool b3SphericalJoint_IsMotorEnabled( b3JointId jointId );
 void b3SphericalJoint_SetMotorVelocity( b3JointId jointId, b3Vec3 motorVelocity );
 b3Vec3 b3SphericalJoint_GetMotorVelocity( b3JointId jointId );
 b3Vec3 b3SphericalJoint_GetMotorTorque( b3JointId jointId );
 void b3SphericalJoint_SetMaxMotorTorque( b3JointId jointId, float torque );
 float b3SphericalJoint_GetMaxMotorTorque( b3JointId jointId );
 b3JointId b3CreateWeldJoint( b3WorldId worldId, const b3WeldJointDef* def );
 void b3WeldJoint_SetLinearHertz( b3JointId jointId, float hertz );
 float b3WeldJoint_GetLinearHertz( b3JointId jointId );
 void b3WeldJoint_SetLinearDampingRatio( b3JointId jointId, float dampingRatio );
 float b3WeldJoint_GetLinearDampingRatio( b3JointId jointId );
 void b3WeldJoint_SetAngularHertz( b3JointId jointId, float hertz );
 float b3WeldJoint_GetAngularHertz( b3JointId jointId );
 void b3WeldJoint_SetAngularDampingRatio( b3JointId jointId, float dampingRatio );
 float b3WeldJoint_GetAngularDampingRatio( b3JointId jointId );
 b3JointId b3CreateWheelJoint( b3WorldId worldId, const b3WheelJointDef* def );
 void b3WheelJoint_EnableSuspension( b3JointId jointId, bool flag );
 bool b3WheelJoint_IsSuspensionEnabled( b3JointId jointId );
 void b3WheelJoint_SetSuspensionHertz( b3JointId jointId, float hertz );
 float b3WheelJoint_GetSuspensionHertz( b3JointId jointId );
 void b3WheelJoint_SetSuspensionDampingRatio( b3JointId jointId, float dampingRatio );
 float b3WheelJoint_GetSuspensionDampingRatio( b3JointId jointId );
 void b3WheelJoint_EnableSuspensionLimit( b3JointId jointId, bool flag );
 bool b3WheelJoint_IsSuspensionLimitEnabled( b3JointId jointId );
 float b3WheelJoint_GetLowerSuspensionLimit( b3JointId jointId );
 float b3WheelJoint_GetUpperSuspensionLimit( b3JointId jointId );
 void b3WheelJoint_SetSuspensionLimits( b3JointId jointId, float lower, float upper );
 void b3WheelJoint_EnableSpinMotor( b3JointId jointId, bool flag );
 bool b3WheelJoint_IsSpinMotorEnabled( b3JointId jointId );
 void b3WheelJoint_SetSpinMotorSpeed( b3JointId jointId, float speed );
 float b3WheelJoint_GetSpinMotorSpeed( b3JointId jointId );
 void b3WheelJoint_SetMaxSpinTorque( b3JointId jointId, float torque );
 float b3WheelJoint_GetMaxSpinTorque( b3JointId jointId );
 float b3WheelJoint_GetSpinSpeed( b3JointId jointId );
 float b3WheelJoint_GetSpinTorque( b3JointId jointId );
 void b3WheelJoint_EnableSteering( b3JointId jointId, bool flag );
 bool b3WheelJoint_IsSteeringEnabled( b3JointId jointId );
 void b3WheelJoint_SetSteeringHertz( b3JointId jointId, float hertz );
 float b3WheelJoint_GetSteeringHertz( b3JointId jointId );
 void b3WheelJoint_SetSteeringDampingRatio( b3JointId jointId, float dampingRatio );
 float b3WheelJoint_GetSteeringDampingRatio( b3JointId jointId );
 void b3WheelJoint_SetMaxSteeringTorque( b3JointId jointId, float torque );
 float b3WheelJoint_GetMaxSteeringTorque( b3JointId jointId );
 void b3WheelJoint_EnableSteeringLimit( b3JointId jointId, bool flag );
 bool b3WheelJoint_IsSteeringLimitEnabled( b3JointId jointId );
 float b3WheelJoint_GetLowerSteeringLimit( b3JointId jointId );
 float b3WheelJoint_GetUpperSteeringLimit( b3JointId jointId );
 void b3WheelJoint_SetSteeringLimits( b3JointId jointId, float lowerRadians, float upperRadians );
 void b3WheelJoint_SetTargetSteeringAngle( b3JointId jointId, float radians );
 float b3WheelJoint_GetTargetSteeringAngle( b3JointId jointId );
 float b3WheelJoint_GetSteeringAngle( b3JointId jointId );
 float b3WheelJoint_GetSteeringTorque( b3JointId jointId );
 bool b3Contact_IsValid( b3ContactId id );
 b3ContactData b3Contact_GetData( b3ContactId contactId );

'''
